### ISSUE TITLE
why not upgrade to springboot2.0.0.RELEASE?

### ISSUE THREAD

**Issue by boboyada** [microservice-patterns/ftgo-application#3]
why not upgrade to springboot2.0.0.RELEASE,and spring5?
this codes has used :
springboot1.4.5.RELEASE,
springboot1.5.4.RELEASE,
springboot2.0.0.M3,
........
version too much!

**Comment by cer** [comment]
Agreed. Working on it.
See this branch:  https://github.com/microservice-patterns/ftgo-application/tree/wip-spring-boot-2
