### ISSUE TITLE
wip-restaurant-order-rename branch

### ISSUE THREAD

**Issue by andy-suruceanu** [microservice-patterns/ftgo-application#4]
Hi Chris,

I've noticed there was a branch of renaming from RestaurantOrder to "Ticket", and RestaurantOrderService to "KitchenService" and more. You've merged that to master so far. The thing is that I've noticed that "Restaurant" entity/ aggregate class from the ftgo-kitchen-service has still having the names for @table and @collectionTable interfaces:

- @Table(name = "restaurant_order_service_restaurants") - should be renamed to "kitchen_service_restaurants"?

- @CollectionTable(name = "restaurant_order_service_restaurant_menu_items") - "kitchen_service_restaurant_menu_items"?

**Comment by cer** [comment]
Thanks for pointing this out

**Comment by cer** [comment]
Fixed with https://github.com/microservice-patterns/ftgo-application/commit/f8f147338cf0b90af01067adf06035eac6ec9380
